name: vectors_and_matrices
description: The classes vector and matrices along with few properties defined on them.
version: 1.0.0
homepage: https://github.com/pete-g00/vectors_and_matrices

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  corextensions: ^1.0.0
  collection: ^1.14.13

dev_dependencies:
  pedantic: ^1.8.0
